services:
  - type: web
    name: dokum-kayit-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: creds.json
